extends: airbnb-base

env:
  node: true
  mocha: true

parserOptions:
  ecmaVersion: 2018
  sourceType: script

rules:
  'comma-dangle': ['error', 'never']
  'strict': ['error', 'global']
  'no-trailing-spaces': ['error', { skipBlankLines: true }]
  'max-len': ['error', { 'code': 120 }]
  'no-underscore-dangle': ['error', 'never']
  'semi': ['error', 'never']
  'object-curly-newline': ['error', { consistent: true }]